# Change these first
owner: binhonglee # Your GitHub organization or username, where this repository lives
repo: GT-Status # The name of this repository

sites:
  - name: API
    url: https://api.globetrotte.com/api/passwd
  - name: Web
    url: https://globetrotte.com
  - name: AI Agent
    url: https://api.globetrotte.com/api/agent_status

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.globetrotte.com
  # baseUrl: /GT-Status
  logoUrl: https://globetrotte.com/favicon.svg
  name: Status
  introTitle: ""
  introMessage: Operational status for all GlobeTrotte services
  favicon: https://globetrotte.com/favicon.ico
  faviconSvg: https://globetrotte.com/favicon.svg
  navbar:
    - title: Home
      href: https://globetrotte.com
  #   - title: Status
  #     href: /

workflowSchedule:
  graphs: "40 * * * *"
  responseTime: "20 * * * *"
  staticSite: "0 * * * *"
  summary: "40 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
